/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wizardtds_vscode;

import org.junit.jupiter.api.Test;

import wizardtds_vscode.com.wizardtdshooter.view.Game;
import wizardtds_vscode.com.wizardtdshooter.view.Window;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        Window classUnderTest = new Window(100, 100, "Sample", new Game());
        assertNotNull(classUnderTest.getClass(), "app should have a greeting");
    }
}
